name: Deploy website to S3
on: [push]
jobs:
  Deployment:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-1
    steps:
      - uses: actions/checkout@v2
      
      - name: Set environment stage
        run: |
          if ${{ github.ref == 'refs/heads/master' }}; then
              echo "branch_name=PROD" >> $GITHUB_ENV
          else
              echo "branch_name=DEV" >> $GITHUB_ENV
          fi

      - name: S3 Sync
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
        env:
          AWS_S3_BUCKET: ${{ secrets[format('{0}_AWS_S3_BUCKET', env.branch_name)] }}
          AWS_ACCESS_KEY_ID: ${{ secrets[format('{0}_AWS_ACCESS_KEY_ID', env.branch_name)] }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets[format('{0}_AWS_SECRET_ACCESS_KEY', env.branch_name)] }}
          AWS_REGION: ${{ env.AWS_REGION }}   # optional: defaults to us-east-1
