name: Deploy website to S3
on: [push]
jobs:
  Deployment:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-1
    steps:
      - uses: actions/checkout@master
      
      - name: Set environment stage
        run: |
          if ${{ github.ref == 'refs/heads/master' }}; then
              echo "environment=PROD" >> $GITHUB_ENV
          else
              echo "environment=DEV" >> $GITHUB_ENV
          fi

      - name: S3 Sync
        uses: shallwefootball/s3-upload-action@master
        with:
        #   args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
          aws_key_id: ${{ secrets[format('{0}_AWS_ACCESS_KEY_ID', env.environment)] }}
          aws_secret_access_key: ${{ secrets[format('{0}_AWS_SECRET_ACCESS_KEY', env.environment)]}}
          aws_bucket: ${{ secrets[format('{0}_AWS_S3_BUCKET', env.environment)] }}
          source_dir: '.'
          destination_dir: ''