name: Deploy website to S3
on: [push]
jobs:
  Deployment:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-1
    steps:
      - name: Set master env
        if: ${{ github.ref == 'refs/heads/master' }}
        run: echo "branch_name=PROD" >> $GITHUB_ENV
      - name: Set dev env
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: echo "branch_name=DEV" >> $GITHUB_ENV

      - name: S3 Sync
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets[format('{0}_AWS_S3_BUCKET', env.branch_name)] }}
          AWS_ACCESS_KEY_ID: ${{ secrets[format('{0}_AWS_ACCESS_KEY_ID', env.branch_name)] }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets[format('{0}_AWS_SECRET_ACCESS_KEY', env.branch_name)] }}
          AWS_REGION: ${{ env.AWS_REGION }}   # optional: defaults to us-east-1
